orders/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^list/', OrderListView.as_view(), name="list"),
]


shipping/api/urls.py
"""
Shipping Urls Api
"""

# Django Rest
from rest_framework.routers import SimpleRouter
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path

# Views
from .views import *

app_name = 'api_shipping'

router = SimpleRouter()

urlpatterns = [
    path('create/', CreateShippingApiView.as_view(), name='create'),
]

urlpatterns += router.urls

urlpatterns = format_suffix_patterns(urlpatterns)

shipping/urls.py
"""
 Shipping Urls
"""

# Django
from django.conf.urls import url, include
from django.urls import path

# Views
from .views import *

urlpatterns = [
    url(r'^list/', ShippingListView.as_view(), name="list"),

    path(
        route='create_shipping/',
        view=ShippingCreateView.as_view(),
        name='create'
    ),

    path(
        route='mark_received_shipping/<uuid:shipping_id>/',
        view=mark_received_shipping,
        name="mark_received_shipping"
    ),
]

store_omni/urls.py
"""store URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
)
from django.conf.urls import url,include
from django.contrib import admin

# View
from accounts import views as accounts_views
from store_omni import views as store_views

# Django RestFRamework
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('shipping/', include(('shipping.urls', 'shipping'), namespace='shipping')),

    # Api Rest Urls
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url(r'^api/(?P<version>(v1|v2))/accounts/', include(('accounts.api.urls', 'api_accounts'), namespace='api_accounts')),
    url(r'^api/(?P<version>(v1|v2))/products/', include(('products.api.urls', 'api_products'), namespace='api_products')),
    url(r'^api/(?P<version>(v1|v2))/orders/', include(('orders.api.urls', 'api_orders'), namespace='api_orders')),
    url(r'^api/(?P<version>(v1|v2))/payments/', include(('payments.api.urls', 'api_payments'), namespace='api_payments')),
    url(r'^api/(?P<version>(v1|v2))/shipping/', include(('shipping.api.urls', 'api_shipping'), namespace='api_shipping')),

    path(
      route='',
      view=accounts_views.login_view,
      name='store_login'
    ),
    path(
      route='404',
      view=store_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=store_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shipping/models.py
"""Shipping model."""

import uuid

# Django
from django.db import models

# Models
from accounts.models import AuditBaseAbstract

# Signals
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


class Shipping(AuditBaseAbstract):
    """Shipping model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    orders = models.ManyToManyField('orders.Order', related_name='shipping_orders')
    received = models.BooleanField(
        default=False
    )
    created_by = models.ForeignKey(
        'accounts.User',
        verbose_name="Created by",
        help_text="Who created it?",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="%(class)s_created_by",
        editable=False
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return "{} - {}".format(
            self.uuid,
            self.created_by,
        )

@receiver(post_save, sender=Shipping)
def update_order(sender, instance, created, **kwargs):
    """
    Signal post save for update status orders  at shipping
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    for order in instance.orders.all():
        order.sent = True
        order.save()

shipping/forms.py
"""
Payments forms.
"""

# Django
from django import forms

# Models
from .models import *
from orders.models import Order


class ShippingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ShippingForm, self).__init__(*args, **kwargs)
        self.fields['orders'] = forms.ModelMultipleChoiceField(
            queryset=Order.objects.filter(
                sent=False,
                paid_out=True
            )
        )

    class Meta:
        model = Shipping
        fields = [
            'orders'
        ]

shipping/api/views.py
"""
Shipping Api Views
"""

# Django Restframework
from rest_framework import permissions, status
from rest_framework.views import APIView
from rest_framework.response import Response

# Models
from shipping.models import Shipping

# Serializers
from .serializer import ShippingSerializer

# Celery
from shipping.tasks import send_notification


class CreateShippingApiView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, version):
        if not 'orders' in request.data:
            return Response([{
                'status': 'error',
                'msg': 'orders is required',
            }], status=status.HTTP_400_BAD_REQUEST)

        orders = request.data.getlist('orders')

        if orders:
            shipping_created = Shipping.objects.create(
                created_by=request.user
            )

            shipping_created.orders.add(*orders)
            shipping_created.save()

            """Send notification with Celery to User"""
            list_email_users = shipping_created.orders.all().values_list('created_by__email', flat=True)
            send_notification.delay(list(list_email_users), "Has sent your products")

            return Response({
                'results': ShippingSerializer(shipping_created).data
            }, status=status.HTTP_200_OK)

        return Response({
            'results': 'success'
        }, status=status.HTTP_200_OK)

shipping/views.py
"""Payments Views."""

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.views.generic.list import ListView

# Models
from .models import *
from orders.models import *

# Forms
from .forms import ShippingForm

# Celery
from .tasks import send_notification

class ShippingListView(LoginRequiredMixin, ListView):
    model = Shipping
    queryset = model.objects.all()
    template_name = 'shipping/list.html'
    paginate_by = 10


class ShippingCreateView(LoginRequiredMixin, CreateView):
    model = Shipping
    form_class = ShippingForm
    template_name = 'shipping/create.html'

    def form_valid(self, form, **kwargs):
        """
        Validate and save
        """
        if form.is_valid():
            orders = form.cleaned_data.get("orders")

            shipping_created = Shipping.objects.create(
                created_by=self.request.user,
            )

            shipping_created.orders.add(*list(orders))
            shipping_created.save()

            """Send notification with Celery to User"""
            list_email_users = shipping_created.orders.all().values_list('created_by__email', flat=True)
            send_notification.delay(list(list_email_users), "Has sent your products")

            msg = 'Order sent and notify successfully.'
            messages.info(
                self.request,
                msg
            )

            return HttpResponseRedirect(reverse('shipping:list'))


    def get_context_data(self, **kwargs):
        context = super(ShippingCreateView, self).get_context_data(**kwargs)
        context['exists_orders_to_send'] = Order.objects.filter(
            sent=False
        )
        return context


def mark_received_shipping(request, shipping_id):
    """
    Method for method to mark a shipment as received and notify the user
    """
    shipping = Shipping.objects.get(uuid=shipping_id)
    shipping.received = True
    shipping.save()

    """Send notification with Celery to User"""
    list_email_users = shipping.orders.all().values_list('created_by__email', flat=True)
    send_notification.delay(list(list_email_users), "We are happy that you received your products")

    msg = 'Shipping marks as received successfully.'
    messages.info(
        request,
        msg
    )

    return HttpResponseRedirect(reverse('shipping:list'))

templates/shipping/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% block head_content %}
    <title>Shipping</title>
{% endblock %}
{% block container %}
    <div class="row">
        <div class="col-lg-2 ml-auto">
            <a href="{% url 'shipping:list' %}" class="btn btn-secondary btn-block">go to list Shipping</a>
        </div>
        <div class="col-lg-12">
            <h3 class="mb-5">Shipping</h3>
        </div>
        {% if exists_orders_to_send %}
            <div class="col-lg-12">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="col-lg-10">
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field|add_class:'form-control' }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-2">
                            <button type="submit" class="btn btn-block btn-primary">Send</button>
                        </div>
                    </form>
        </div>
        {% else %}
            <p>You haven't orders to send.</p>
        {% endif %}

    </div>
{% endblock %}

templates/shipping/list.html
{% extends "base.html" %}
{% load humanize %}
{% block head_content %}
	<title>Shipping</title>
{% endblock %}
{% block container %}
	<div class="row justify-content-center">
        <h3>Shipping</h3>
        <div class="col-lg-12">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                         <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
		<div class="col-lg-12">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th scope="col">UUID</th>
                        <th scope="col">Received</th>
                        <th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					{% for shipping in object_list %}
						<tr>
							<td>{{ shipping.uuid }}</td>
							<td>
                                {% if shipping.received  %}
                                    <i class="fas fa-check-circle text-success"></i>
                                {% else %}
                                    <i class="fas fa-times-circle text-danger"></i>
                                {% endif %}
                            </td>
							<td>
                                {% if not shipping.received  %}
                                    <a href="{% url 'shipping:mark_received_shipping' shipping_id=shipping.uuid %}"
                                       class="btn btn-block btn-primary">
                                        Mark as received
                                    </a>
                                {% endif %}
                            </td>
						</tr>
                    {% empty %}
                        <p class="text-center">No shipping available</p>
					{% endfor %}
				</tbody>
			</table>
            <a href="{% url 'shipping:create' %}"
               class="btn btn-block btn-primary">
                Go to prepare new shipment
            </a>
		</div>
        {% include 'shared/pagination.html' %}
	</div>
{% endblock %}