orders/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^list/', OrderListView.as_view(), name="list"),
]


products/api/urls.py
"""
Products Urls Api
"""

# Django Rest
from rest_framework.routers import SimpleRouter
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path

# Views
from .views import *

app_name = 'api_products'

router = SimpleRouter()
router.register(r"", ProductViewSet)

urlpatterns = [
    path('add_to_order/<uuid:product_id>/', ProductAddOrderApiView.as_view(), name='add_to_order'),
]

urlpatterns += router.urls

urlpatterns = format_suffix_patterns(urlpatterns)

products/urls.py
"""
 Products Urls
"""

# Django
from django.conf.urls import url, include
from django.urls import path

# Views
from .views import *

urlpatterns = [
    url(r'^create/', ProductCreateView.as_view(), name="create"),
    url(r'^list/', ProductListView.as_view(), name="list"),
    path(
        route='add_product_order_select/<uuid:product_id>/',
        view=ProductOrderCreateView.as_view(),
        name='add_product_order_select'
    ),
    path(
        route='edit/<pk>/',
        view=ProductsUpdateView.as_view(),
        name='edit'
    ),
    path(
        route='delete/<pk>/',
        view=ProductsDeleteView.as_view(),
        name='delete'
    ),
    path(
        route='products/<uuid:product_id>/add_product_order_default/',
        view=add_product_order_default,
        name='add_product_order_default'
    ),
    path(
        route='check_exists_order/<uuid:product_id>/',
        view=check_exists_order,
        name="check_exists_order"
    ),
]


store_omni/urls.py
"""store URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
)
from django.conf.urls import url,include
from django.contrib import admin

# View
from accounts import views as accounts_views
from store_omni import views as store_views

# Django RestFRamework
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('shipping/', include(('shipping.urls', 'shipping'), namespace='shipping')),

    # Api Rest Urls
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url(r'^api/(?P<version>(v1|v2))/accounts/', include(('accounts.api.urls', 'api_accounts'), namespace='api_accounts')),
    url(r'^api/(?P<version>(v1|v2))/products/', include(('products.api.urls', 'api_products'), namespace='api_products')),
    url(r'^api/(?P<version>(v1|v2))/orders/', include(('orders.api.urls', 'api_orders'), namespace='api_orders')),
    url(r'^api/(?P<version>(v1|v2))/payments/', include(('payments.api.urls', 'api_payments'), namespace='api_payments')),
    url(r'^api/(?P<version>(v1|v2))/shipping/', include(('shipping.api.urls', 'api_shipping'), namespace='api_shipping')),

    path(
      route='',
      view=accounts_views.login_view,
      name='store_login'
    ),
    path(
      route='404',
      view=store_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=store_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
"""Products model."""

import uuid

# Django
from django.db import models

# Models
from accounts.models import AuditBaseAbstract


class Product(AuditBaseAbstract):
    """Products model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.TextField(
        max_length=50,
        help_text='Descriptive name.'
    )
    description = models.TextField(
        max_length=600,
    )
    price = models.PositiveIntegerField(default=0)
    enabled = models.BooleanField(
        default=True,
        help_text=(
            'Helps to easily distinguish the condition of the product.'
        )
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

products/forms.py
"""
Product forms.
"""

# Django
from django import forms

# Models
from .models import *


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

products/api/views.py
"""
Products Api Views
"""

# Django Restframework
from rest_framework.viewsets import ModelViewSet
from rest_framework import permissions, status
from rest_framework.views import APIView
from rest_framework.response import Response

# Models
from products.models import Product
from orders.models import Order, OrderProducts

# Serializers
from .serializer import ProductSerializer

# Pagination
from store_omni.pagination import StandardResultsSetPagination

#Djanfo
from django.db import IntegrityError


class ProductViewSet(ModelViewSet):
    """
        View for management crud at Products
    """
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = ProductSerializer
    queryset = Product.objects.all()

    def list(self, request, version):
        queryset = self.queryset
        if not self.request.user.is_superuser or not self.request.user.is_staff:
            """
            Filter product by enabled=True if is an
            user no privileges admin 
            """
            queryset = queryset.filter(
                enabled=True
            )

        paginator = StandardResultsSetPagination()
        result_page = paginator.paginate_queryset(queryset, request)
        serializer = self.serializer_class(result_page, many=True, context={'user': request.user})

        return paginator.get_paginated_response(serializer.data)


class ProductAddOrderApiView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, version, product_id):
        user_order = Order.objects.filter(
            created_by=request.user,
            paid_out=False,
            sent=False,
        ).first()
        product = Product.objects.get(uuid=product_id)

        """
        It is validated if the user has an order created
        to associate the new product,
        otherwise a new order is created by default
        """
        if user_order:
            try:
                OrderProducts.objects.create(
                    order=user_order,
                    product=product
                )
            except IntegrityError:
                return Response([{
                    'status': 'error',
                    'msg': 'product already exists at order user',
                }], status=status.HTTP_400_BAD_REQUEST)
        else:
            order_created = Order.objects.create(
                created_by=request.user
            )

            try:
                OrderProducts.objects.create(
                    order=order_created,
                    product=product
                )
            except IntegrityError:
                return Response([{
                    'status': 'error',
                    'msg': 'product already exists at order user',
                }], status=status.HTTP_400_BAD_REQUEST)

        return Response({
            'results': 'Success'
        }, status=status.HTTP_200_OK)

products/views.py
"""Products Views."""

# Django
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

# Models
from .models import *
from orders.models import *


# Forms
from .forms import ProductForm
from orders.forms import OrderProductForm


class ProductCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/create_update.html'
    success_url = reverse_lazy('products:list')
    success_message = 'Successfully created product.'


class ProductsUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/create_update.html'
    success_url = reverse_lazy('products:list')
    success_message = 'Successfully updated product.'


class ProductsDeleteView(SuccessMessageMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('products:list')
    success_message = 'Successfully deleted product.'


class ProductListView(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Product
    queryset = model.objects.all()
    template_name = 'products/list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        if not self.request.user.is_superuser or not self.request.user.is_staff:
            """
            Filter product by enabled=True if is an
            user no privileges admin 
            """
            queryset = queryset.filter(
                enabled=True
            )
        return queryset


class ProductOrderCreateView(LoginRequiredMixin, CreateView):
    model = OrderProducts
    form_class = OrderProductForm
    template_name = 'products/add_to_order.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs


    def form_valid(self, form, **kwargs):
        """
        Validate and save
        """
        if form.is_valid():
            product_id = self.kwargs['product_id']
            product = Product.objects.get(pk=product_id)
            order = form.cleaned_data['order']

            order_product_taken = OrderProducts.objects.filter(
                order_id=order.uuid,
                product_id=product.uuid
            ).exists()

            if not order_product_taken:
                """
                It is validated that this product is not associated
                 with this order to be able to associate it.
                """
                order_products = OrderProducts(product=product, **form.cleaned_data)
                order_products.save()

            msg = f'Product added to order {product.name}.'
            messages.info(
                self.request,
                msg
            )

            return HttpResponseRedirect(reverse('products:list'))

    def get_context_data(self, **kwargs):
        context = super(ProductOrderCreateView, self).get_context_data(**kwargs)
        context['product_id'] = self.kwargs['product_id']
        return context


@login_required
def check_exists_order(request, product_id):
    """
    Method for verifying if there is
    a order created for an user
    """
    try:
        Order.objects.get(created_by=request.user, sent=False, paid_out=False)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('products:add_product_order_default', args=(
            product_id,
        )))
    except MultipleObjectsReturned:
        pass

    return HttpResponseRedirect(reverse('products:add_product_order_select', args=(
        product_id,
    )))


@login_required
def add_product_order_default(request, product_id):
    """
    It allows us to add product to order
    :param product_id: id product to add
    """
    order = Order.objects.create(
        created_by=request.user
    )

    product = Product.objects.get(
        uuid=product_id
    )

    OrderProducts.objects.create(
        order=order,
        product=product
    )

    msg = f'Product added to order {product.name}.'
    messages.info(
        request,
        msg
    )

    return HttpResponseRedirect(reverse('products:list'))




templates/products/add_to_order.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block head_content %}
    <title>Product - Add to Order</title>
{% endblock %}
{% block container %}
    <div class="row">
        <div class="col-lg-2 ml-auto">
            <a href="{% url 'products:list' %}" class="btn btn-secondary btn-block">go to list products</a>
        </div>
        <div class="col-lg-12">
            <h3 class="mb-5">Product - Add to Order</h3>
        </div>
        <div class="col-lg-12">
            <form method="POST">
                {% csrf_token %}
                <div class="col-lg-10">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field|add_class:'form-control' }}
                        </div>
                    {% endfor %}
                </div>
                <div class="col-lg-2">
                    <button type="submit" class="btn btn-block btn-primary">Save</button>
                </div>
            </form>
        </div>

        <div class="col-lg-2 mt-5 ml-3">
            <a href="{% url 'products:add_product_order_default' product_id=product_id %}" class="btn btn-block btn-warning">Add to new order</a>
        </div>
    </div>
{% endblock %}

templates/products/create_update.html
{% extends "base.html" %}
{% load humanize %}
{% load widget_tweaks %}
{% block head_content %}
    <title>Products</title>
{% endblock %}
{% block container %}
    <div class="row">
        <div class="col-lg-2 ml-auto">
            <a href="{% url 'products:list' %}" class="btn btn-secondary btn-block">go to list products</a>
        </div>
        <div class="col-lg-12">
            <h3 class="mb-5">Products</h3>
        </div>
        <div class="row w-100">
                <div class="col-lg-6">
                    <form method="POST" class="my-5">
                        {% csrf_token %}
                        <div class="col-lg-10">
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field|add_class:'form-control' }}
                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-2">
                            <button type="submit" class="btn btn-block btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
    </div>
{% endblock %}

templates/products/list.html
{% extends "base.html" %}
{% load humanize %}
{% block head_content %}
	<title>Products</title>
{% endblock %}
{% block container %}
	<div class="row justify-content-center">

        <div class="col-lg-2">
            <h3 class="">Products</h3>
        </div>

        {% if user.is_superuser or user.is_staff %}
            <div class="col-lg-2 ml-auto">
                <a href="{% url 'products:create' %}" class="btn btn-secondary btn-block">go to create product</a>
            </div>
        {% endif %}

        <div class="col-lg-12">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                         <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
		<div class="col-lg-12">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th scope="col">Product name</th>
						<th scope="col">Product description</th>
                        <th scope="col">Price</th>
                        {% if user.is_superuser or user.is_staff %}
                            <th scope="col">Enabled</th>
                        {% endif %}
                        <th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					{% for product in object_list %}
						<tr>
							<td>{{ product.name }}</td>
							<td>{{ product.description }}</td>
							<td>$ {{ product.price|intcomma }}</td>
                            {% if user.is_superuser or user.is_staff %}
                                <td>
                                    {% if product.enabled  %}
                                        <i class="fas fa-check-circle text-success"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle text-danger"></i>
                                    {% endif %}
                                </td>
                            {% endif %}
							<td>
                                {% if user.is_superuser or user.is_staff %}
                                    <a href="{% url 'products:edit' pk=product.uuid %}">
                                        <i class="fas fa-edit text-warning"></i>
                                    </a>
                                    <a href="{% url 'products:delete' pk=product.uuid %}">
                                        <i class="fas fa-trash text-danger"></i>
                                    </a>
                                {% else %}
                                    <a href="{% url 'products:check_exists_order' product_id=product.uuid %}"
                                       class="btn btn-block btn-primary w-50">
                                        Add to my order
                                    </a>
                                {% endif  %}
                            </td>
						</tr>
                    {% empty %}
                        <p class="text-center">No products available</p>
					{% endfor %}
				</tbody>
			</table>
		</div>
        {% include 'shared/pagination.html' %}
	</div>
{% endblock %}

templates/products/product_confirm_delete.html
{% extends "base.html" %}
{% block head_content %}
    <title>Product Delete</title>
{% endblock %}
{% block container %}
    <div class="row justify-content-center">
        <h3>Product Delete</h3>
        <div class="col-lg-12">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-lg-12">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <button type="submit" class="btn btn-block btn-danger w-25">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}