accounts/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from .views import *

urlpatterns = [
    # Management
    path(
        route='login/',
        view=login_view,
        name='login'
    ),
    path(
        route='signup/',
        view=signup_view,
        name='signup'
    ),
    path(
        route='logout/',
        view=logout_view,
        name='logout'
    ),
]

orders/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^list/', OrderListView.as_view(), name="list"),
]


store_omni/urls.py
"""store URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
)
from django.conf.urls import url,include
from django.contrib import admin

# View
from accounts import views as accounts_views
from store_omni import views as store_views

# Django RestFRamework
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('shipping/', include(('shipping.urls', 'shipping'), namespace='shipping')),

    # Api Rest Urls
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url(r'^api/(?P<version>(v1|v2))/accounts/', include(('accounts.api.urls', 'api_accounts'), namespace='api_accounts')),
    url(r'^api/(?P<version>(v1|v2))/products/', include(('products.api.urls', 'api_products'), namespace='api_products')),
    url(r'^api/(?P<version>(v1|v2))/orders/', include(('orders.api.urls', 'api_orders'), namespace='api_orders')),
    url(r'^api/(?P<version>(v1|v2))/payments/', include(('payments.api.urls', 'api_payments'), namespace='api_payments')),
    url(r'^api/(?P<version>(v1|v2))/shipping/', include(('shipping.api.urls', 'api_shipping'), namespace='api_shipping')),

    path(
      route='',
      view=accounts_views.login_view,
      name='store_login'
    ),
    path(
      route='404',
      view=store_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=store_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/base_public.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>
    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.resolver_match.app_name == 'products' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:list' %}">Products
                    <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item {% if request.resolver_match.app_name == 'orders' %}active{% endif %}">
                <a class="nav-link" href="{% url 'orders:list' %}">Orders
                    <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_superuser or user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.app_name == 'shipping' %}active{% endif %}"
                       href="{% url 'shipping:list' %}">Shipping</a>
                </li>
            {% endif  %}
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                href="#" id="navbarDropdownMenuLink"
                role="button" data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
                    {{ user }}
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">logout</a>
                </div>
            </li>
        {% endif  %}
        </ul>
    </div>
</nav>