orders/api/urls.py
"""
Orders Urls Api
"""
from rest_framework.routers import SimpleRouter
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path

# Views
from .views import *

app_name = 'api_orders'

router = SimpleRouter()

urlpatterns = [
    path('list/', OrderListView.as_view(), name='list'),
]

urlpatterns += router.urls

urlpatterns = format_suffix_patterns(urlpatterns)

orders/urls.py
from django.conf.urls import url, include

from .views import *

urlpatterns = [
    url(r'^list/', OrderListView.as_view(), name="list"),
]


payments/urls.py
"""
 Payment Urls
"""

# Django
from django.conf.urls import url, include
from django.urls import path

# Views
from .views import *

urlpatterns = [
    path(
        route='pay_orders/',
        view=PayOrdersCreateView.as_view(),
        name='pay_orders'
    ),
]

store_omni/urls.py
"""store URL Configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import (
    path,
)
from django.conf.urls import url,include
from django.contrib import admin

# View
from accounts import views as accounts_views
from store_omni import views as store_views

# Django RestFRamework
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('shipping/', include(('shipping.urls', 'shipping'), namespace='shipping')),

    # Api Rest Urls
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url(r'^api/(?P<version>(v1|v2))/accounts/', include(('accounts.api.urls', 'api_accounts'), namespace='api_accounts')),
    url(r'^api/(?P<version>(v1|v2))/products/', include(('products.api.urls', 'api_products'), namespace='api_products')),
    url(r'^api/(?P<version>(v1|v2))/orders/', include(('orders.api.urls', 'api_orders'), namespace='api_orders')),
    url(r'^api/(?P<version>(v1|v2))/payments/', include(('payments.api.urls', 'api_payments'), namespace='api_payments')),
    url(r'^api/(?P<version>(v1|v2))/shipping/', include(('shipping.api.urls', 'api_shipping'), namespace='api_shipping')),

    path(
      route='',
      view=accounts_views.login_view,
      name='store_login'
    ),
    path(
      route='404',
      view=store_views.not_found_view,
      name='not_found'
    ),
    path(
      route='500',
      view=store_views.server_error_view,
      name='server_error'
    )

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
"""Orders model."""

import uuid

# Django
from django.db import models

# Models
from accounts.models import AuditBaseAbstract

# Signals
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver


class Order(AuditBaseAbstract):
    """Orders model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    amount = models.PositiveIntegerField(default=0)
    paid_out = models.BooleanField(
        'paid_out',
        default=False,
        help_text=(
            'Helps to easily distinguish the status pay order.'
        )
    )
    sent = models.BooleanField(
        default=False,
        help_text=(
            'Helps to easily distinguish the status Shipping order.'
        )
    )
    created_by = models.ForeignKey(
        'accounts.User',
        verbose_name="Created by",
        help_text="Who created it?",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="%(class)s_created_by",
        editable=False
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return "{} - {} - {}".format(
            self.uuid,
            self.amount,
            self.created_by
        )


class OrderProducts(models.Model):
    """Order Products model."""
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order = models.ForeignKey('orders.Order', on_delete=models.CASCADE)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE)

    class Meta:
        unique_together = (('order', 'product'),)

    def __str__(self):
        return '{} - {}: ${}'.format(
            self.order.uuid,
            self.product.name,
            self.order.amount
        )


@receiver(post_save, sender=OrderProducts)
def update_amount_order(sender, instance, created, **kwargs):
    """
    Signal post save for update amount for an order
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    if created:
        order = Order.objects.get(uuid=instance.order.uuid)
        order.amount = order.amount+instance.product.price
        order.save()




orders/forms.py
"""
Order forms.
"""

# Django
from django import forms

# Models
from .models import *


class OrderProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(OrderProductForm, self).__init__(*args, **kwargs)
        self.fields['order'] = forms.ModelChoiceField(
            queryset=Order.objects.filter(
                created_by=user,
                paid_out=False,
                sent=False,
            )
        )

    class Meta:
        model = OrderProducts
        fields = [
            'order'
        ]

orders/api/views.py
"""
Products Api Views
"""

# Django Restframework
from rest_framework import permissions
from rest_framework.generics import ListAPIView

# Models
from orders.models import Order

# Serializers
from .serializer import OrderSerializer

# Pagination
from store_omni.pagination import StandardResultsSetPagination


class OrderListView(ListAPIView):
    """
        View for management list at Orders
    """
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = OrderSerializer
    queryset = Order.objects.all()
    pagination_class = StandardResultsSetPagination

    def get_queryset(self):
        queryset = Order.objects.all()
        if not self.request.user.is_superuser or not self.request.user.is_staff:
            """
            Filter Order by created_by if is an
            user no privileges admin 
            """
            queryset = queryset.filter(
                created_by=self.request.user
            )

        return queryset

orders/views.py
"""Products Views."""

# Django
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

# Models
from .models import *


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    queryset = model.objects.all()
    template_name = 'orders/list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        if not self.request.user.is_superuser or not self.request.user.is_staff:
            """
            Filter Order by created_by if is an
            user no privileges admin 
            """
            queryset = queryset.filter(
                created_by=self.request.user
            )
        return queryset





templates/orders/list.html
{% extends "base.html" %}
{% load humanize %}
{% block head_content %}
	<title>Products</title>
{% endblock %}
{% block container %}
	<div class="row justify-content-center">
        <h3>Orders</h3>
        <div class="col-lg-12">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                         <div class="alert alert-info {% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
		<div class="col-lg-12">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
                        {% if user.is_superuser or user.is_staff %}
                            <th scope="col">User</th>
                        {% endif  %}
						<th scope="col">UUID</th>
						<th scope="col">Products</th>
                        <th scope="col">Paid out</th>
                        <th scope="col">Sent out</th>
                        <th scope="col">Total</th>
					</tr>
				</thead>
				<tbody>
					{% for order in object_list %}
						<tr>
                            {% if user.is_superuser or user.is_staff %}
                                <td>{{ order.created_by.email }}</td>
                            {% endif  %}
							<td>{{ order.uuid }}</td>
							<td>
                                {% for orderproduct in order.orderproducts_set.all %}
                                    <p>{{ orderproduct.product.name }} - $ {{ orderproduct.product.price|intcomma }}</p>
                                {% endfor %}
                            </td>
							<td>
                                {% if order.paid_out  %}
                                    <i class="fas fa-check-circle text-success"></i>
                                {% else %}
                                    <i class="fas fa-times-circle text-danger"></i>
                                {% endif %}
                            </td>
                            <td>
                                {% if order.sent  %}
                                    <i class="fas fa-check-circle text-success"></i>
                                {% else %}
                                    <i class="fas fa-times-circle text-danger"></i>
                                {% endif %}
                            </td>
                            <td>$ {{ order.amount|intcomma }}</td>
						</tr>
                    {% empty %}
                        <p class="text-center">No orders available</p>
					{% endfor %}
				</tbody>
			</table>
            {% if object_list|length > 0 %}
                <a href="{% url 'payments:pay_orders' %}"
                   class="btn btn-block btn-primary w-25">
                    Go to pay
                </a>
            {% endif %}
		</div>
        {% include 'shared/pagination.html' %}
	</div>
{% endblock %}